# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: anaconda 2019.07 python 3.7
channels:
- defaults

dependencies:
- python=3.7.3
# https://docs/anaconda.com/anaconda/packages/py3.7_win-64/
- anaconda=2019.07
- pytest-xdist
