# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python>=3.7.3
# Anaconda 2019.03 python 3.7
- jupyter>=1.0.0
- matplotlib>=3.0.3
- numpy>=1.16.2
- pandas>=0.24.2
- pluggy>=0.11
- pytest>=4.3.1
- scipy>=1.2.1
- statsmodels>=0.9.0
- sympy>=1.3
- pytest-xdist>=1.28.0
- requests
