# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python=3.6
# Anaconda 5.0.1 python 3.6
- jupyter=1.0.0
- matplotlib=2.1.0
- numpy=1.13.3
- pytest=3.2.1
- pandas=0.23.4
- scipy=0.19.1
- statsmodels=0.9.0
- sympy=1.1.1
- pytest-xdist=1.24.1
- requests
- cython
