# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
name: anaconda 4.2 python 3.5

channels:
- defaults

dependencies:
- python=3.5
# https://docs.anaconda.com/anaconda/packages/old-pkg-lists/4.2.0/py35/
- anaconda=4.2
- pytest-xdist
