# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: anaconda 5.0.1 python 3.6
channels:
- defaults

dependencies:
- python=3.6
# https://docs.anaconda.com/anaconda/packages/old-pkg-lists/5.0.1/py3.6_win-64/
- anaconda=5.0.1
- pytest-xdist=1.24.1
