# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python=3.7.4
# Anaconda 2019.10 python 3.7
# https://docs/anaconda.com/anaconda/packages/py3.7_win-64/
- cython=0.29.13
- jupyter=1.0.0
- lxml=4.4.1
- matplotlib=3.1.1
- numpy=1.16.5
- pandas=0.25.1
- pluggy=0.13.0
- pytest=5.2.1
- requests=2.22.0
- scipy=1.3.1
- seaborn=0.9.0
- statsmodels=0.10.1
- sympy=1.4
- xlwt=1.3.0
- pytest-xdist
