# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: anaconda 2019.03 python 3.7.3
channels:
- defaults

dependencies:
- python=3.7.3
# https://docs.anaconda.com/anaconda/packages/old-pkg-lists/2019.03/py3.7_win-64/
- anaconda=2019.03
- pytest-xdist<1.27.0
