# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python>=3.7
- jupyter>=1.0.0
- matplotlib>=2.2.3
- numpy>=1.15.1
- pandas>=0.23.4
- pytest>=3.8.0
- scipy>=1.1.0
- statsmodels>=0.9.0
- sympy>=1.1.1
