# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: anaconda 2018.12 python 3.7.1
channels:
- defaults

dependencies:
- python=3.7.1
# https://docs.anaconda.com/anaconda/packages/old-pkg-lists/2018.12/py3.7_win-64/
- anaconda=2018.12
- pytest-xdist=1.26.1
