# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: travis_anaconda_jupyter
channels:
- defaults

dependencies:
- python=3.6
# Anaconda 5.0.1 python 3.6
- numpy=1.13.3
- scipy=0.19.1
- sympy=1.1.1
- jupyter=1.0.0
- pytest=3.2.1
- matplotlib=2.1.0
- pandas=0.23.4
- statsmodels=0.8.0
- cython=0.26.1
- requests=2.18.4
