# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter

name: anaconda 5.3.0 python 3.7
channels:
- defaults

dependencies:
- python=3.7
# https://docs.anaconda.com/anaconda/packages/py3.7_win-64/
- anaconda=5.3.0
- pytest-xdist=1.26.1
